version: "3.8"
services:
  keg-regulator:
    image: ${IMAGE}
    tty: true
    stdin_open: true
    privileged: true
    build:
      context: ${KEG_CONTEXT_PATH}
      dockerfile: ${KEG_DOCKER_FILE}
      args:
        - DOC_APP_PATH
        - GIT_KEY
        - KEG_IMAGE_FROM
        - KEG_EXEC_CMD
        - KEG_NM_INSTALL
        - NODE_ENV
    container_name: ${CONTAINER_NAME}
    environment:
      - DOC_APP_PATH
      - DOC_APP_PORT
      - DOC_FEATURES_PATH
      - DOC_STEPS_PATH
      - HUB_HOST
      - HUB_PORT
      - KEG_EXEC_CMD
      - KEG_NM_INSTALL
      - NODE_ENV
      - TEST_FILTER_TAGS
      - WINDOW_HEIGHT
      - WINDOW_WIDTH
    ports:
      - ${DOC_APP_PORT}:${DOC_APP_PORT}
    volumes:
      - ${KEG_CONTEXT_PATH}/tests/reports:/keg/keg-regulator/tests/reports
    depends_on:
      - "selenium-hub"
      - "chrome"
      - "firefox"
  
  selenium-hub:
    image: selenium/hub:${SELENIUM_VERSION}
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug:${SELENIUM_VERSION}
    # image: selenium/node-chrome:${SELENIUM_VERSION}
    container_name: 'selenium-chrome'
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - VNC_NO_PASSWORD=1
      - WINDOW_HEIGHT
      - WINDOW_WIDTH
    ports:
      - ${CHROME_PORT}:${DOC_CHROME_PORT}
      - ${CHROME_VNC_PORT}:${CHROME_VNC_PORT}

  firefox:
    image: selenium/node-firefox-debug:${SELENIUM_VERSION}
    # image: selenium/node-firefox:${SELENIUM_VERSION}
    container_name: 'selenium-firefox'
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - VNC_NO_PASSWORD=1
      - WINDOW_HEIGHT
      - WINDOW_WIDTH
    ports:
      - ${FIREFOX_PORT}:${DOC_FIREFOX_PORT}
      - ${FIREFOX_VNC_PORT}:${DOC_FIREFOX_VNC_PORT}
