version: "3.8"
services:
  keg-regulator:
    image: ${IMAGE}
    tty: true
    stdin_open: true
    privileged: true
    build:
      context: ${KEG_CONTEXT_PATH}
      dockerfile: ${KEG_DOCKER_FILE}
      args:
        - DOC_APP_PATH
        - GIT_KEY
        - KEG_IMAGE_FROM
        - KEG_EXEC_CMD
        - KEG_NM_INSTALL
        - NODE_ENV
    container_name: ${CONTAINER_NAME}
    environment:
      - DOC_APP_PATH
      - DOC_APP_PORT
      - DOC_FEATURES_PATH
      - DOC_STEPS_PATH
      - HEADLESS
      - HUB_HOST
      - HUB_PORT
      - KEG_EXEC_CMD
      - KEG_NM_INSTALL
      - NODE_ENV
      - TEST_FILTER_TAGS
      - WINDOW_HEIGHT
      - WINDOW_WIDTH
    ports:
      - ${DOC_APP_PORT}:${DOC_APP_PORT}
    volumes:
      - ${KEG_CONTEXT_PATH}/tests/reports:/keg/keg-regulator/tests/reports
    depends_on:
      - "selenium-hub"
      - "chrome"
      - "firefox"
  keg-novnc:
    image: gotget/novnc
    container_name: ${NO_VNC_CONTAINER}
    command: --vnc regulator.kegdev.xyz:${DOC_VNC_PORT} --listen ${NO_VNC_PORT}
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - VNC_NO_PASSWORD=1
      - WINDOW_HEIGHT
      - WINDOW_WIDTH
    ports:
      - ${NO_VNC_PORT}:${NO_VNC_PORT}
    depends_on:
      - "selenium-hub"
      - "chrome"
      - "firefox"
