version: "3.8"
services:
  kegcomponents:
    image: ${IMAGE}
    tty: true
    stdin_open: true
    privileged: true
    build:
      context: ${CONTEXT_PATH}
      dockerfile: ${CONTEXT_DOCKER_FILE}
      args:
        GIT_COMPONENTS_URL: ${GIT_COMPONENTS_URL}
        GIT_KEY: ${GIT_KEY}
        DOC_APP_PATH: ${DOC_APP_PATH}
    container_name: ${CONTAINER_NAME}
    environment:
      - ENV
      - EXEC_CMD
      - DOC_APP_PATH
      - DOC_CLI_PATH
      - DOC_COMPONENTS_PATH
      - DOC_RETHEME_PATH
      - GIT_CLI_URL
      - GIT_COMPONENTS_URL
      - GIT_RETHEME_URL
      - IMAGE_FROM
      - NM_INSTALL
      - NODE_ENV
    ports:
      - 80:${STORYBOOK_PORT}