version: "3.8"
services:
  tap:
    privileged: true
    build:
      context: ${KEG_CONTEXT_PATH}
      dockerfile: ${KEG_DOCKER_FILE}
      args:
        - DOC_APP_PATH
        - GIT_APP_URL
        - KEG_BUILD_TYPE
        - KEG_CORE_PATH
        - KEG_IMAGE_FROM
        - KEG_NODE_VERSION
    environment:
      - CHOKIDAR_USEPOLLING
      - DOC_APP_PATH
      - DOC_BUILD_PATH
      - DOC_CLI_PATH
      - DOC_CORE_PATH
      - DOC_COMPONENTS_PATH
      - DOC_RESOLVER_PATH
      - DOC_RETHEME_PATH
      - DOC_JSUTILS_PATH
      - KEG_EXEC_CMD
      - KEG_DOCKER_EXEC
      - KEG_NM_INSTALL
      - KEG_NODE_VERSION
      - NODE_ENV
      - TAP
