version: "3.8"
networks:
  {{ dockerNetwork }}:
    external: true
services:
  {{ service }}:
    image: {{ imageFrom }}
    container_name: {{ container }}
    tty: true
    stdin_open: true
    networks:
      - {{ dockerNetwork }}
    build:
      context: {{ buildContextPath }}
      dockerfile: {{ dockerPath }}