version: "3.8"
services:
  kegcore:
    image: ${IMAGE}
    tty: true
    stdin_open: true
    privileged: true
    build:
      context: ${CONTEXT_PATH}
      dockerfile: ${CONTEXT_DOCKER_FILE}
      args:
        - ENV
        - EXEC_CMD
        - DOC_APP_PATH
        - DOC_CLI_PATH
        - DOC_CORE_PATH
        - DOC_COMPONENTS_PATH
        - DOC_RESOLVER_PATH
        - DOC_RETHEME_PATH
        - GIT_CLI_URL
        - GIT_CORE_URL
        - GIT_COMPONENTS_URL
        - GIT_KEY
        - GIT_RETHEME_URL
        - GIT_RESOLVER_URL
        - GIT_TAP_URL
        - IMAGE_FROM
        - NM_INSTALL
        - NODE_ENV
    container_name: ${CONTAINER_NAME}
    environment:
      - ENV
      - EXEC_CMD
      - DOC_APP_PATH
      - DOC_CLI_PATH
      - DOC_CORE_PATH
      - DOC_COMPONENTS_PATH
      - DOC_RESOLVER_PATH
      - DOC_RETHEME_PATH
      - GIT_CLI_URL
      - GIT_CORE_URL
      - GIT_COMPONENTS_URL
      - GIT_RETHEME_URL
      - GIT_RESOLVER_URL
      - GIT_TAP_URL
      - IMAGE_FROM
      - KEG_CORE_PROGRESS
      - NM_INSTALL
      - NODE_ENV
    ports:
      - ${EXPO_DEBUG_PORT}:${EXPO_DEBUG_PORT}
      - 80:${EXPO_APP_PORT}