module.exports = {
  ...require('./bddService'),
  ...require('./buildService'),
  ...require('./composeService'),
  ...require('./containerService'),
  ...require('./destroyService'),
  ...require('./getServiceArgs'),
  ...require('./mutagenService'),
  ...require('./remoteExecService'),
  ...require('./packageService'),
  ...require('./restartService'),
  ...require('./serviceOptions'),
  ...require('./startService'),
  ...require('./stopService'),
  ...require('./syncService'),
}